<h1 class="display-4 home-h1">My TodoList !</h1>
    <a href="controller/inprogress_task.php">
        <button class="home-btn btn btn-danger">Mes tâches à faire</button>
    </a>
    <a href="controller/finish_task.php">
        <button class="home-btn btn btn-success">Mes tâches finies</button>
    </a>

<a href="controller/task_list.php">
    <button class="home-btn btn btn-warning">Liste des tâches</button>
</a>

    <a href="controller/add_task.php">
<button class="home-btn btn btn-info">Ajouter une tâche</button>
</a>
