<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cerulean/bootstrap.min.css">
    <link rel="stylesheet" href="../css/style.css">
    <title> Todolist Garance </title>
</head>
<body>
<header class="mb-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="../index.php">MyTodoList</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor03">
            <ul class="navbar-nav mr-auto">
                <li <?php if($page == "home") echo 'class="nav-item active"'; ?>>
                    <a class="nav-link" href="../index.php">Accueil</a>
                </li>
                <li <?php if($page == "todo") echo 'class="nav-item active"'; ?>>
                    <a class="nav-link" href="inprogress_task.php">À faire</a>
                </li>
                <li <?php if($page == "done") echo 'class="nav-item active"'; ?>>
                    <a class="nav-link" href="finish_task.php">Finie</a>
                </li>
                <li <?php if($page == "task_list") echo 'class="nav-item active"'; ?>>
                    <a class="nav-link" href="task_list.php">Liste des tâches</a>
                </li>
                <li <?php if($page == "add_task") echo 'class="nav-item active"'; ?>>
                    <a class="nav-link" href="add_task.php">Ajouter une tache</a>
                </li>
        </div>
    </nav>
</header>
<main class="container">
    <?php include '../views/'.$content ?>
</main>
</body>
</html>